name: demo_app2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  modal_bottom_sheet: ^2.1.2
  intl: ^0.18.1
  grouped_list: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: publicsans-extrabold
      fonts:
        - asset: assets/fonts/publicsans-extrabold.ttf
    - family: publicsans-bold
      fonts:
        - asset: assets/fonts/publicsans-bold.ttf
    - family: publicsans-semibold
      fonts:
        - asset: assets/fonts/publicsans-semibold.ttf
    - family: publicsans-medium
      fonts:
        - asset: assets/fonts/publicsans-medium.ttf
    - family: publicsans-regular
      fonts:
        - asset: assets/fonts/publicsans-regular.ttf